version: '3.1'
volumes:
  data:
services:
  postgres:
    container_name: gaiapi_postgresql
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gaiapi_dev
    restart: always
    ports: 
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/gaiapi/data